### ISSUE TITLE
Adds space after default value in function parameter

### ISSUE THREAD

**Issue by arve0** [chenxsan/vscode-standard-format#2]
This

``` js
function reducer (state = numbers, action) {
```

becomes this

``` js
function reducer (state = numbers , action) {
```

**Comment by chenxsan** [comment]
It's actually an issue in standard-format https://github.com/maxogden/standard-format/issues/140.

**Comment by chenxsan** [comment]
Since [standard-format](https://github.com/maxogden/standard-format#important-note) might be deprecated later. I would suggest using [vscode-standardjs 0.0.19](https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs). A new `Format code with standard` command has been added, and this issue doesn't exist any more.
