### ISSUE TITLE
Fails to add space after function name es6.

### ISSUE THREAD

**Issue by MatthewOverall** [chenxsan/vscode-standard-format#3]
It works with functions such as this.

``` javascript
function myMethod() {
}
```

turns into ->

``` javascript
function myMethod () {
}
```

however the following is not formatted

``` javascript
var blah = {
  _myMethod() {
  }
}
```

**Comment by MatthewOverall** [comment]
Actually discovered that the issue isn't with the plugin but rather the formatter found here.
https://github.com/maxogden/standard-format/issues/116

**Comment by chenxsan** [comment]
Since [standard-format](https://github.com/maxogden/standard-format#important-note) might be deprecated later. I would suggest using [vscode-standardjs 0.0.19](https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs). A new `Format code with standard` command has been added, and it could format:

```
var blah = {
  _myMethod() {
  }
}
```

into

```
var blah = {
  _myMethod () {
  }
}
```
