### ISSUE TITLE
When using format on save, file cannot be saved and always has some change

### ISSUE THREAD

**Issue by alexsorokoletov** [chenxsan/vscode-standard-format#6]
When you save a file, plugin for some reason makes it unsaved again. 
Looks like either vscode is adding a line in the end and plugin removes it or backwards.
Usually not a problem, unless you are debugging with vscode.

VS Code Version 1.3.1 for OS X.

**Comment by chenxsan** [comment]
If you enable [`formatOnSave`](https://github.com/chenxsan/vscode-standard-format/commit/29da7dcf0ab8a74f6f11cc03149ba504ea1ab9e1#diff-45327f86d4438556066de133327f4ca2R38), then it's expected, since standard-format would format the file when `vscode.workspace.onDidSaveTextDocument` event fired. I guess we need second save here, and event like [onPreSaveTextDocument](https://github.com/Microsoft/vscode/issues/239) would be much more suitable.

For the moment, I would suggest disabling `formatOnSave` until this is fixed :)

**Comment by alexsorokoletov** [comment]
@chenxsan thank you, did as suggested. Would appreciate fix on that. Thank you for the plugin!

**Comment by chenxsan** [comment]
We're now moving to the new [vscode-standardjs](https://github.com/chenxsan/vscode-standardjs) forked from vscode-eslint, so this bug won't get fixed.
